### ISSUE TITLE
Stalls during Startup

### ISSUE THREAD

**Issue by pablocawichii** [oae/kaizoku#106]
### Describe the bug

I am having a bug where the initialization script does not complete. It does not get past the `/etc/cont-init.d/40-config` step.

This is my docker container log.

![image](https://github.com/oae/kaizoku/assets/30267397/fbdc8811-bceb-4598-b2a4-93ca09db153d)

### Reproduction steps

1. Copy Docker-compose file from Repository.
2. Replace service: app: build with `image: ghcr.io/oae/kaizoku:latest`
3. Run `docker compose up -d`

### Expected behavior

I expected the docker container to start without issue.

### Additional context

The container does start. However, it takes about 15 minutes to go from the above image to started.

**Comment by Casuallynoted** [comment]
Having this bug as well, stops at exactly the same place.

**Comment by pablocawichii** [comment]
@Casuallynoted 
Maybe its an issue with startup, but after a couple hours I found I was able to access the content.
