### ISSUE TITLE
[Docker] Changing Mangal config doesn't work 

### ISSUE THREAD

**Issue by vodkapmp** [oae/kaizoku#11]
I am trying to change the config values og mangal and they do not seem to stick.
Using "mangal config set" doesn't change anything, as it seems the default location (/config/.config/mangal) isn't being used.
Changing something in the mangal.toml in the default location also doesn't change the mangal settings.

![image](https://user-images.githubusercontent.com/70449815/197944818-5f303cf3-4978-40e2-b3c5-2cbc3f0ca6cf.png)

I have not tested this with kaizoku outside of docker, tested with mangal on desktop and settings configuration values works as it should then.

**Comment by metafates** [comment]
My guess would be that `MANGAL_CONFIG_PATH` env variable needs to be set in the [Dockerfile](https://github.com/oae/kaizoku/blob/main/docker/Dockerfile)

**Comment by oae** [comment]
These are enforced in Dockerfile for kaizoku to function correctly

https://github.com/oae/kaizoku/blob/9da4606dcca47a800a4488780d052c74dcd153a2/docker/Dockerfile#L74-L79

**Comment by oae** [comment]
I will implement a settings page that can configure mangal settings as stated in #7

**Comment by vodkapmp** [comment]
Can the comicinfo xml be overriden without any severe issues?
It's kinda annoying that the comicinfo.xml contains the publish date of the series and not the chapter, which makes the date of every chapter in tachiyomi (via komga) show up as released on the publish date for the series.

So a chapter released last week might be marked as released in 2014 if that is when the manga first started.

**Comment by metafates** [comment]
@vodkapmp I think I can make an option in mangal to disable date generation for each chapter in ComicInfo.xml, so no need to completely it. Unfortunately, Anilist API (which mangal uses to pull information) does not provide release date for each chapter

**Comment by oae** [comment]
you can try passing the environment variable to Dockerfile.
