### ISSUE TITLE
Issue with /data mount

### ISSUE THREAD

**Issue by Sumokai31** [oae/kaizoku#128]
### Describe the bug

I've an issue on mangas downloaded, it seems that there are stored in the container size and not in the /data set in the docker-compose:

My docker-compose:
![image](https://github.com/oae/kaizoku/assets/78795023/e5ede4db-9fdd-402a-bc72-0b1908dbfb1a)

the docker ps --size:
![image](https://github.com/oae/kaizoku/assets/78795023/d5b82ca0-7133-47a6-9b13-4cb54dc643e3)

Inside the kaizoku container:
![image](https://github.com/oae/kaizoku/assets/78795023/9aa358c9-b5fb-468b-a8c2-506fccd12ea6)

in the docker inspect:
![image](https://github.com/oae/kaizoku/assets/78795023/02f20a27-d41d-4e83-ae0a-3b7d0aad9866)

in the directory mount for /data:
![image](https://github.com/oae/kaizoku/assets/78795023/95ee8639-8961-4eb6-9489-7fbc18082e9f)

### Reproduction steps

1. add new manga 

### Expected behavior

the mangas downloaded should be in the location set for /data

**Comment by ElryWeeb** [comment]
Yeah thats not it chief. 
It works fine, you just need to do give correct file paths...
Like /data or /media/manga

**Comment by Enfinit** [comment]
Did you ever find a solution to this? Currently running into the same problem. Everything is writing to the /config and /logs folders fine but nothing shows up in the /data folder.

**Comment by Sumokai31** [comment]
Hello,

Still go the same issue as you @Enfinit, no solution found.
@ElryWeeb Not sure I'm doing something wrong, the file path is correct for me, I'm running around 30 containers on my homeserver, never got this issue.
**{{ path_kaizoku_data }}** is just a variable in my ansible playbook for an existing path **/mnt/storage/KAIZOKU** and in the docker compose I mount it in **/data**, this is not working for me :-( . No issue with /logs and /config.

**Comment by mg-dev25** [comment]
@Sumokai31 @Enfinit 
So after testing, I've found a solution. When /data is set in the docker-compose file nothing happen but when I set the path to /app/Manga, I found that the data are transfer to /data. So I set Two path for the same dir outside the container and it work.

volumes:
  - /T7_Gama/data/manga:/app/Manga
  - /T7_Gama/data/manga:/data

**Comment by Sumokai31** [comment]
Thank you @mg-dev25 !!
Your solution is working for me too.
Thing strange, mangas are downloaded in the /data volume directly and ignore the /data/Manga volume, not an issue in my case.
