### ISSUE TITLE
Feature Suggestion: SQLite option instead of Postgres

### ISSUE THREAD

**Issue by Kussie** [oae/kaizoku#13]
It would be great if we had the option to use SQLite instead of Postgres.  Personally i dislike having to run a full featured RDBMS, makes it easier to backup individual projects and such as well.

**Comment by oae** [comment]
Prisma with SQLite doesn't support some data types that are being used. So I am not currently planning on adding support for it.

**Comment by Kussie** [comment]
Do you have an example out of curiosity? The Prisma docs don't make any mention of any such limitations that are currently being used?  The only thing it doesn't support is JSON types, which according to the schema and migrations isn't being used anyway.

**Comment by oae** [comment]
It doesn't support array types

https://github.com/oae/kaizoku/blob/9da4606dcca47a800a4488780d052c74dcd153a2/prisma/schema.prisma#L48-L58
