### ISSUE TITLE
[Docker] All tasks in bull queue gone after restart

### ISSUE THREAD

**Issue by vodkapmp** [oae/kaizoku#14]
After a restart of my docker containers I noticed that everything in Bull Dashboard is gone.
I stop all my dockers 3 times a week to do a quick backup of important docker related data (configs etc) after yesterdays backup cycle I noticed that everything in the bull dashboard is now gone.
![image](https://user-images.githubusercontent.com/70449815/198212398-f4a32ab1-4927-4414-b9a6-1e366aea1b25.png)

Is there some mount point for the docker that I should've had that isn't mentioned in the docker-compose file?

Also is there a faster way to get my scheduled tasks back than re-adding every manga one by one?

**Comment by oae** [comment]
If you recreated the container it might have been deleted. Mount should be under `redis:/data` like [here](https://github.com/oae/kaizoku#deployment). Currently, no way to get the queue back. I will add it in the next version.

**Comment by vodkapmp** [comment]
Thanks!
I do have redis:/data mounted, but it seems something unrelated to kaizoku went wrong and the data was destroyed.

I assume a way to add the queue back might be part of the changes one would implement with #9

**Comment by oae** [comment]
All tasks will be recreated on startup. Also you can update manga to create individual tasks
