### ISSUE TITLE
custom schedule for checking new chapters

### ISSUE THREAD

**Issue by Intecancoder** [oae/kaizoku#150]
### Feature Description

Add selection for choosing timing for checking chapters (i.e., Monday at 9AM)

### Solution you would like

Allow users to choose which day of the week, or which time of the day for the checking

### Alternatives you have considered

Can you tell me where in the code for this action? I would try to learn and change it

**Comment by oae** [comment]
you can use cron in interval section. 
![image](https://github.com/oae/kaizoku/assets/1043714/5344d888-d395-4c7f-a31f-83b0a0390218)

**Comment by Intecancoder** [comment]
I realized that 0.00005s after I posted that and dont know how to delete the issues. Apologies, I am new to Github and apparently a dumbass.
