### ISSUE TITLE
[Feature Request] Webhook and or Discord notifications

### ISSUE THREAD

**Issue by ojmaster** [oae/kaizoku#158]
### Feature Description

Hello, I was wondering if it was possible to add a notification type for webhooks, and if possible discord? These are common notification types I use and would really appreciate it if it was added.

**Comment by oae** [comment]
Hello, You can already do this with apprise integration in the settings 

![image](https://github.com/oae/kaizoku/assets/1043714/84f354af-6b59-4e0a-9359-e3ee981b3815)

Documentation is here https://github.com/caronc/apprise/wiki/Notify_discord
