### ISSUE TITLE
Custom intervals do not work

### ISSUE THREAD

**Issue by vodkapmp** [oae/kaizoku#29]
### Describe the bug

When trying to set any interval that isn't the default ones it fails with error "invalid interval"

### Reproduction steps

1. Set an interval that isn't one of the default ones
2. Get error

### Expected behavior

Custom intervals should work and not error

### Additional context

I've tried all kinds of cronstrue intervals and none of them will stick
![image](https://user-images.githubusercontent.com/70449815/200137618-3c2304b9-9f59-4016-a1cf-635762941a74.png)

**Comment by oae** [comment]
You need to give a cron expression. For example `0 4 * * *`.

**Comment by vodkapmp** [comment]
Ah, I assumed it would be able to parse it from human readable to cron expression.

**Comment by oae** [comment]
It will translate to human-readable format but not the other way :)
