### ISSUE TITLE
Additional Sources

### ISSUE THREAD

**Issue by Typhonragewind** [oae/kaizoku#32]
### Feature Description

Not sure if it's already in your plans or not, but consider adding the (non-duplicate) sources contained in https://github.com/metafates/mangal-scrapers, such as AsuraScans and ComicK.
They seem to be ready to be imported and used by mangal.

**Comment by oae** [comment]
I don't plan to add more sources to Kaizoku itself. But you can mount any mangal scrapers to `/config/.config/mangal/sources` and use them.
