### ISSUE TITLE
Select language for each manga, source, or instance of Kaizoku

### ISSUE THREAD

**Issue by PlummerWare** [oae/kaizoku#34]
### Feature Description

The ability to select language when setting up each Manga to download. Understandably not all sources have multiple languages.  

### Alternatives you have considered

Is there a text file or database location I can alter to have sources be scraped in another language (Japanese)? Happy to run multiple instances of Kaizoku in containers for each language to accomplish this.

### Additional context

Multi Lingual household.  English and Japanese. Regardless of your response. Enjoying Kaizoku so far. Great job.

**Comment by oae** [comment]
Kaizoku uses mangal under the hood. So you can create a new scraper and use it. See [this comment](https://github.com/oae/kaizoku/issues/32#issuecomment-1305496891) on how to mount it.
