### ISSUE TITLE
Kavita Integration

### ISSUE THREAD

**Issue by majora2007** [oae/kaizoku#36]
### Feature Description

I saw that you recently added Komga integration, I would love it if Kavita could also have integration. Kavita has a large install base and is a prominent software for manga collectors. 

https://github.com/Kareadita/Kavita

### Solution you would like

Inform Kavita when a manga has been downloaded via ScanFolder api (which tells Kavita to scan said folder into the system)

### Additional context

I am the developer of Kavita, please reach out if there is anything I can do to help drive integration. A lot of my users are now using this software, so providing integration would be great.

**Comment by oae** [comment]
Hi,

Thank you for the suggestion. Is there any API documentation that I can check?

**Comment by majora2007** [comment]
There are some swagger docs on our demo instance.

https://demo.kavitareader.com/swagger

If you need an auth token, the demo urls are on the GitHub and the token is in local storage.

**Comment by oae** [comment]
Thank you. I will work on this feature next.
