### ISSUE TITLE
Changing download location

### ISSUE THREAD

**Issue by RealStickman** [oae/kaizoku#40]
### Feature Description

I'd love to use kaizoku, however my current folder structure makes this rather difficult.  
It would be awesome if I could manually specify the download location of a manga.  

You already present the field of the download location to the user, so maybe this is already planned on?  
![image](https://user-images.githubusercontent.com/61015582/204025883-cfadc713-8040-428e-be8b-a9affed1b5a3.png)  

### Solution you would like

Manual entry of the path or a graphical path chooser. I'm guessing the first one would be much easier to implement though.

**Comment by oae** [comment]
That field is for previewing and it cannot be changed. Manga paths are generated and sanitized dynamically based on the title. I haven't tried it but you can try mounting individual manga directories with matching locations that are being shown in Kaizoku to docker.
