### ISSUE TITLE
Slow Down the Download queue

### ISSUE THREAD

**Issue by Bijoejinj** [oae/kaizoku#42]
### Feature Description

When downloading a Manga with many Chapters its not uncommon for the later chapters to fail downloading since Kaizoku is sending tens of requests per second.

### Solution you would like

Limit the Download Rate per chapter. So something like 5 Chapters per 10 seconds or something along those lines.

**Comment by oae** [comment]
Kaizoku uses `mangal` for download operations. So there is no way for it to change the download rate. Kaizoku will try to download it again if an error occurs during a download.
