### ISSUE TITLE
Adding Manhwa

### ISSUE THREAD

**Issue by shedman214** [oae/kaizoku#43]
### Feature Description

Will you be adding Manhwa sites in future updates. One i love to use is Toonily! 

https://toonily.com/

please add  soon

**Comment by oae** [comment]
Hi, Thank you for the suggestion but I don't plan to add any more websites. But you can create/use [mangal scrapers](https://github.com/metafates/mangal#custom-scrapers) with kaizoku. You can copy/mount mangal scrapers under `/config/.config/mangal/sources` and use it

**Comment by shedman214** [comment]
ok how would i add the site. never done it before, but would love to learn how

**Comment by oae** [comment]
You can see some examples [here](https://github.com/metafates/mangal-scrapers). Also, take a look at the [Creating custom scraper](https://github.com/metafates/mangal#creating-a-custom-scraper) section in the mangal repo.

**Comment by shedman214** [comment]
I made this one by editing one of the examples: it wont find any media

--------------------------------------
-- @name    Mangakatana 
-- @url     https://mangakatana.com/
-- @author  metafates 
-- @license MIT
--------------------------------------




----- IMPORTS -----
Html = require("html")
Headless = require('headless')
Time = require("time")
--- END IMPORTS ---




----- VARIABLES -----
Browser = Headless.browser()
Page = Browser:page()
Base = "https://mangakatana.com"
Delay = 1 -- seconds
--- END VARIABLES ---



----- MAIN -----

--- Searches for manga with given query.
-- @param query Query to search for
-- @return Table of tables with the following fields: name, url
function SearchManga(query)
    local url = Base .. "/?s=" .. query
    Page:navigate(url)
    Time.sleep(Delay)

    local mangas = {}

    for i, v in ipairs(Page:elements(".bsx > a")) do
        local manga = { url = v:attribute('href'), name = v:attribute('title') }
        mangas[i + 1] = manga
    end

    return mangas
end


--- Gets the list of all manga chapters.
-- @param mangaURL URL of the manga
-- @return Table of tables with the following fields: name, url
function MangaChapters(mangaURL)
    Page:navigate(mangaURL)
    Time.sleep(Delay)

    local chapters = {}

    for _, v in ipairs(Page:elements("#chapterlist > ul li")) do
        local n = tonumber(v:attribute("data-num"))
        local elem = Html.parse(v:html())
        local link = elem:find("a"):first()

        local chapter = { url = link:attr("href"), name = link:find("span"):first():text() }

        if n ~= nil then
            chapters[n] = chapter
        end
    end

    return chapters
end


--- Gets the list of all pages of a chapter.
-- @param chapterURL URL of the chapter
-- @return Table of tables with the following fields: url, index
function ChapterPages(chapterURL)
    Page:navigate(chapterURL)
    Time.sleep(Delay)

    local pages = {}
    for i, v in ipairs(Page:elements("#readerarea p img")) do
        local p = { index = i, url = v:attribute("src") }
        pages[i + 1] = p
    end

    return pages
end

--- END MAIN ---




----- HELPERS -----
--- END HELPERS ---

-- ex: ts=4 sw=4 et filetype=lua
