### ISSUE TITLE
Some mangas download and some do not

### ISSUE THREAD

**Issue by shedman214** [oae/kaizoku#44]
### Describe the bug

I have been adding mangas to my collection and some have blank chapters but on the site they have many chapters. When the time comes to download them at 00 there is no failed logs but the folder is empty.
![image](https://user-images.githubusercontent.com/32603273/206721620-25d80916-c096-4c68-935c-4988113092b7.png)

![image](https://user-images.githubusercontent.com/32603273/206722874-cbdf2e16-230a-452b-8068-09a6d23c5383.png)

**Comment by oae** [comment]
Can you check the activities and see if there are any delayed/failed jobs for downloads?

**Comment by shedman214** [comment]
there both blank 
![image](https://user-images.githubusercontent.com/32603273/206734996-06372298-3010-4e0d-9678-843ecbb29a2e.png)
![image](https://user-images.githubusercontent.com/32603273/206735039-57d4d6d5-3aa1-414d-a1b4-95d7a69c8f46.png)

**Comment by oae** [comment]
You have almost 3000 waiting jobs. Did you check them? Kaizoku only downloads 10 chapters at a time. Maybe that manga you specified didn't start downloading yet.

**Comment by shedman214** [comment]
Is there a way to force it to download now instead of waiting?

**Comment by oae** [comment]
Unfortunately, there is no way to force it.
