### ISSUE TITLE
[Docker] TRPCClientError When Adding Specific Manga

### ISSUE THREAD

**Issue by themadman0980** [oae/kaizoku#47]
### Describe the bug

I've had issues adding some specific manga to my collection. When I get to the end of the process I get the following error:

"TRPCClientError: Cannot find the Yu-Gi-Oh! Duelist."

This has happened for a few series but not all (I can still normally add most series).

### Reproduction steps

1. Add new Manga
2. Set source to Manganato
3. Select Yugioh! Duelist OR Yugioh! Millenium World
4.  Select any time interval
5. Error on main page: TRPCClientError: Cannot find the Yu-Gi-Oh! Duelist.

### Additional context

I have tried investigating logs but couldn't see any errors. It's currently on info level so I assumed that should include any errors?

**Comment by oae** [comment]
This is not related to kaizoku. mangal cannot find related mangas. I think this is related to `!` inside the name. 

`mangal inline --source Manganato --include-anilist-manga --query "Yu-Gi-Oh! Duelist" --manga exact --chapters all -j`

**Comment by themadman0980** [comment]
Maybe not a big deal, but could be helpful to have a more clear error message? Something like "Error: Mangal was unable to find related mangas at [SOURCE]".

New users like me will see that and assume that there was an issue with Kaizoku while searching, not that there simply weren't any matches.

Up to you. :)
