### ISSUE TITLE
[Docker] Mangasee source broken

### ISSUE THREAD

**Issue by vodkapmp** [oae/kaizoku#5]
The Mangasee source is broken.
From the logs:
`"Failed to get available sources: err: Error: Command failed with exit code 1: mangal inline --source Mangasee --query xxxx -j\nX /config/.config/mangal/sources/Mangasee.lua:46: attempt to index a non-table object(nil) with key 'page'\nstack traceback:\n\t/config/.config/mangal/sources/Mangasee.lua:46: in main chunk\n\t[G]: ?"}`

**Comment by oae** [comment]
It seems like headless chrome cannot start when you select the mangasee. But I couldn't reproduce this. https://github.com/oae/kaizoku/blob/5713b206a0dbfb329ef3ac8466eca4a2c93b05a5/docker/mangal/sources/Mangasee.lua#L46

**Comment by vodkapmp** [comment]
There is a bunch of missing dependencies for headless chrome to work in the docker container.

I installed these that I found in a random list somwhere saying they are needed dependencies for headless chrome: `ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils`

Mangasee now works as it should.

**Comment by oae** [comment]
After using `ldd` on chrome executable, this was the minimal dependency array:

```yaml
RUN apt install libglib2.0-0 \
  libnss3 \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libcups2 \
  libdrm2 \
  libxcb1 \
  libxkbcommon0 \
  libxcomposite1 \
  libxdamage1 \
  libxfixes3 \
  libxrandr2 \
  libgbm1 \
  libpango-1.0-0 \
  libcairo2 \
  libasound2 && \ 
```
