### ISSUE TITLE
Support for discord notifications

### ISSUE THREAD

**Issue by HamzaM** [oae/kaizoku#54]
### Feature Description

It would be nice if we could have discord notifications or an integration directly with Notifiarr https://github.com/Notifiarr/notifiarr

**Comment by oae** [comment]
This functionality is already in Kaizoku. You can use apprise to [send notifications](https://github.com/caronc/apprise/wiki/Notify_discord).

**Comment by HamzaM** [comment]
I will use that then, thanks !
