### ISSUE TITLE
Save config 

### ISSUE THREAD

**Issue by HamzaM** [oae/kaizoku#57]
### Feature Description

Settings/User preferences are not exportable

### Solution you would like

Having a config file in the kaizoku config folder would be nice, a file like a json or something where the settings are saved in case we re deploy later and want to save our settings.

A backup system can also work instead of a config file, and of course we can also add to the config/backup a list of the mangas monitored maybe ?

**Comment by oae** [comment]
All settings and manga information are saved in the PostgreSQL database. You export/import from the DB.

**Comment by HamzaM** [comment]
Thanks for the quick response !
