### ISSUE TITLE
Mangasee broken in ver 1.4.0, works in 1.3.1

### ISSUE THREAD

**Issue by doorssbm** [oae/kaizoku#58]
### Describe the bug

On version 1.4.0 Mangasee source returns: No result found... no matter what is searched.
![image](https://user-images.githubusercontent.com/122519473/212016604-d285d7ed-d848-4cc2-bbed-c6f94350ee36.png)
[kaizoku.log](https://github.com/oae/kaizoku/files/10399591/kaizoku.log)
On version 1.3.1 Mangasee source functions as expected
![image](https://user-images.githubusercontent.com/122519473/212017460-fab9b682-71d6-48bf-8575-0b8a5b4daa71.png)
[kaizoku.log](https://github.com/oae/kaizoku/files/10399629/kaizoku.log)

### Reproduction steps

On version 1.4.0
1. Add a new manga
2. Select a source: Mangasee
3. click Next step
4. Search for a manga: type 'bleach'
5. click arrow (or hit enter)
6. No result found...

### Expected behavior

Return results for search of Mangasee source like it did in version 1.3.1

### Additional context

It appears that downgrading to version 1.3.1 fixes the issue entirely.

Thanks for all your work on this, it is amazing!

**Comment by oae** [comment]
Hi,

On 1.4.0, I can get results. 
![image](https://user-images.githubusercontent.com/1043714/212020220-aed50f32-2a38-4a50-a4fe-ba70415000a1.png)


Can you try removing the `rod` folder inside the `/config/.cache/` and restart the container?

**Comment by doorssbm** [comment]
Removed rod folder in the mentioned place, pulled image version 1.4.0, recreated container. Tried same search process and it returned No result found...
[kaizoku.log](https://github.com/oae/kaizoku/files/10400601/kaizoku.log)

**Comment by oae** [comment]
I am able to reproduce this problem now. I will look into this.

**Comment by oae** [comment]
It seems like chrome is crashing. I have no idea what has changed with it. 

![image](https://user-images.githubusercontent.com/1043714/212058105-66fae8e4-93ad-4d3e-b20e-19e5398abdc4.png)

**Comment by oae** [comment]
I found the problem. The chrome version that is being downloaded by mangal has a bug and crashes. Mangal libs need an update for this to be fixed. 

But in the meantime, You can remove `/config/.cache/rod/browser/chromium-1065323/chrome-linux`,  download [chrome](https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1087031/chrome-linux.zip) and extract it to `/config/.cache/rod/browser/chromium-1065323/`.
