### ISSUE TITLE
Feature suggestion: settings ui for mangal

### ISSUE THREAD

**Issue by metafates** [oae/kaizoku#7]
Option to configure mangal directly from kaizoku would be useful.

You can show all available config fields with current value, type and description in json format via `mangal config info --json`. `--json` flag was added since v3.13.0

Set value with `mangal config set --key <key> --value <value>`
Get value with `mangal config get --key <key>`

Though, not all settings would be useful, but you can filter only those that start with specific domain. E.g. `downloader.*` related settings

**Comment by oae** [comment]
That is a good idea. I will add it. But some settings need to be controlled by kaizoku to function.

**Comment by oae** [comment]
This is the WIP design for the settings

![image](https://user-images.githubusercontent.com/1043714/199618319-d0048cc7-5c0e-492e-b41b-c1bb98755e47.png)
