### ISSUE TITLE
Add additional indexers

### ISSUE THREAD

**Issue by wfulcher** [oae/kaizoku#72]
### Feature Description

I think it would be a good idea to make it so we can add additional indexers. The standard set is fine but a lot have rate limits so you have to bounce around and sometimes they are fairly inconsistent. 

Looking on the back end, this appears to be performing a form of scraping. So in theory, it should handle any site that does gallery style comics. 

### Solution you would like

Could be done in a few different ways:

1. Add a menu that allows us to add new indexers
2. Add a config file option that allows us to list custom indexers
3. Add a copy and paste option for the "Add" process that would allow us to input a url for a series we'd like to follow. 

### Alternatives you have considered

Have considered and tried using a local app to scrape and compile, but wouldnt be automated so wont update without intervention or additional scripting.

**Comment by oae** [comment]
Hi, Kaizoku uses mangal for downloading. I don't plan to add any more sources. But you can always add your own. See https://github.com/oae/kaizoku/issues/32#issuecomment-1305496891 and https://github.com/metafates/mangal#creating-a-custom-scraper
