### ISSUE TITLE
Notification to Discord webhook

### ISSUE THREAD

**Issue by Captainpax** [oae/kaizoku#78]
### Feature Description

I use discord to get updates for most of my server stuff and I don't see any updates from kaizoku.

### Solution you would like

When a manga has been "moved" to [queued, scheduled, failed, completed, out-of-sync] send a message to a discord webhook with: the manga name, release date, summary, and cover art. 
here is a quick help with javascript discord webhooks https://github.com/jb3/webhook-discord,https://github.com/JorgenVatle/discord-webhook-ts

### Alternatives you have considered

the cover art might be hard but I seen others do it with imgur API https://apidocs.imgur.com/#intro

### Additional context

UwU <3

**Comment by oae** [comment]
This is already supported using apprise. See https://github.com/oae/kaizoku/issues/54#issuecomment-1377631280

**Comment by Captainpax** [comment]
Can I have an example please? having a hard time following the there guide.

**Comment by Captainpax** [comment]
nvm i got it thanks!

**Comment by UberMentch** [comment]
> 

would you mind sharing what you did? i'm having a hard time figuring out how the format lines up with what the "host" and "url" fields are looking for.
