### ISSUE TITLE
change language 

### ISSUE THREAD

**Issue by delta-whiplash** [oae/kaizoku#79]
hello I am trying to download this manga 
how a realist hero rebuilt the kingdom in french release on mangadex could you guide me please

**Comment by oae** [comment]
Hi,

You should create your own scraper for that. See https://github.com/oae/kaizoku/issues/72#issuecomment-1418185893
You can copy MangaDex to a new file and change parameters to your needs.
 https://github.com/oae/kaizoku/blob/fded3cf2467d0a75adf85d2d345edc98791254ed/docker/mangal/sources/MangaDex.lua#L47 file and change parameters to fit your needs.

**Comment by delta-whiplash** [comment]
I just want to change this to fr everything is already supported
![image](https://user-images.githubusercontent.com/39416418/218865362-2681b064-4b78-4e62-85db-2700a5a99e9c.png)

**Comment by oae** [comment]
For that, you should use "Mangadex", not "MangaDex". After you set the setting as "fr", it should work.

**Comment by delta-whiplash** [comment]
Ok i understand But how can I validate this change everytime I want to change it to fr it don't save the settings
I tried any but same result it go back to en
