### ISSUE TITLE
Wrong metadata + fix wrong match doesn't work

### ISSUE THREAD

**Issue by Typhonragewind** [oae/kaizoku#80]
### Describe the bug

When searching for certain manga, kaizoku doesn't fetch the correct metadata and when trying to use the "fix match" function right before adding, it also doesn't seem to work.

### Reproduction steps

1. Search for the "Radiant" manga (source: manganelo, https://anilist.co/anime/101024/RADIANT/)
2. Select the first result (the one without a proper cover). The metadata for first result is not for the manga in question, instead being for a hentai manga with the same name, I think (Bonus - this also appears when NSFW is deactivated in settings)
3. Try to fix match using AniList ID. Also does not update

### Expected behavior

Correct metadata is not downloaded

### Additional context

When using mangal in CLI, it correctly detects the correct manga (https://anilist.co/anime/101024/RADIANT/) as the first result

Also, here are some logs that might help: https://pastebin.com/C9GRkyat

Thanks for your great work!

**Comment by oae** [comment]
The AniList link you use is for anime. You need to use manga id

**Comment by Typhonragewind** [comment]
Doh, you're right, it seems I had a dumb moment. The manga in talking about is this https://chapmanganelo.com/manga-th90553

And i think the metadata problem comes from that specific manga not being listed in AniList Manga

**Comment by oae** [comment]
There is no manga entry on AniList for Radiant. For example, the AniList id for this link `https://anilist.co/manga/30011/NARUTO/`  is 30011.
