### ISSUE TITLE
Add Publisher Tag to metadata

### ISSUE THREAD

**Issue by ojmaster** [oae/kaizoku#92]
### Feature Description

CBZ files have a publisher tag metadata field and I think it would be nice if it was to tag the CBZ files with the series' publisher. The reader that I host sorts series by publishers so I think it would be useful to have this tag.

**Comment by oae** [comment]
Tagging metadata is handled by [mangal](https://github.com/metafates/mangal). So this is out of Kaizoku's capabilities.
