### ISSUE TITLE
Can't Find Title, Title confirmed to exist.

### ISSUE THREAD

**Issue by eswiig** [oae/kaizoku#94]
### Describe the bug

Kaizoku add new title: 

(no, the His Girlfriend on the left column is not the same one, It's some NTR story)

![image](https://user-images.githubusercontent.com/58608430/235526708-a7999b54-a7a7-4863-878d-d89a5c3ce4f2.png)

Mangal can find the title:

![image](https://user-images.githubusercontent.com/58608430/235526788-2b314b15-bfec-4c1e-94da-b624e3022dfc.png)

Proof title exist (same url as in Mangal)
![image](https://user-images.githubusercontent.com/58608430/235526957-04ba778c-1f55-472e-9e2a-099253017d8a.png)

### Reproduction steps

1. Add Manga
2. Choose Manganato source
3. Search Title

### Expected behavior

Find the manga (would be nice if we could supply direct link)

### Additional context

If screenshots or linking is not allowed, please delete

**Comment by oae** [comment]
That is actually the correct manga but the AniList match is wrong. You can get the id from the anilist and fix the match during the last step. 
![image](https://user-images.githubusercontent.com/1043714/235530647-93065c0e-ef9a-444c-bfa1-19c673ea26f9.png)

**Comment by oae** [comment]
I will add a link to the source site to make it more visible if it is the wrong manga or anilist match.
