### ISSUE TITLE
Kavita integration enhancement

### ISSUE THREAD

**Issue by ShivamAmin** [oae/kaizoku#95]
### Feature Description

I just recently setup Kaizoku, and connected it to my Kavita server. I currently have two libraries, 'Books' and 'Manga'. When Kaizoku updates Kavita, it iterates through all the libraries and updates all of them. Since my Books library is managed by Readarr + Calibre, It doesn't make sense for Kaizoku to update that library each time my 'Manga' library has been updated

### Solution you would like

An option to specify the librar(y|ies) that it should update. 

### Alternatives you have considered

Not connect Kaizoku to Kavita, and just manually refresh my 'Manga' library,

### Additional context

I've got a lot of epubs in my 'Books' library, and while the scan is fast on Kavita's side, it does take a while to skip over everything it has already scanned.

**Comment by eswiig** [comment]
could this  be applied to Komga as well?

**Comment by ShivamAmin** [comment]
Yeah, I don't use Komga, but I took a look at the api docs, and it should be pretty simple.
