### ISSUE TITLE
Custom Download Interval

### ISSUE THREAD

**Issue by ojmaster** [oae/kaizoku#98]
### Feature Description

Is it possible to have this? Some manga release on Wednesdays or every two weeks and I'd like to have those Kaizoku poll those on those certain intervals. Also is it possible to edit the interval after already adding a manga?

**Comment by oae** [comment]
You can add any cron to the interval. You can use https://crontab.guru/ to generate to your liking.

![image](https://user-images.githubusercontent.com/1043714/236633374-0c72f858-e094-45e2-9b0c-ee1247baf77f.png)

If you want to change it after you add it. You can edit the manga from the home screen. 

![image](https://user-images.githubusercontent.com/1043714/236633438-581f1b65-79dd-4833-bdae-4ad6626df0fa.png)
